using Microsoft.VisualStudio.TestTools.UnitTesting.Logging;

namespace kolpet.MazeSolver
{
    [TestClass]
    public class UnitTest1
    {
        #region XMLs
        private const string Level1Xml = @"<Maze>
   <Level>1</Level>
   <StartPoint>
       <Row>9</Row>
       <Column>1</Column>
   </StartPoint>
   <EscapePoint>
       <Row>7</Row>
       <Column>17</Column>
   </EscapePoint>
   <InsideItems>
       <Wall>
           <Row>2</Row>
           <Column>6</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>2</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>3</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>4</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>6</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>8</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>9</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>10</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>11</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>12</Column>
       </Wall>	  
	   <Wall>
           <Row>3</Row>
           <Column>13</Column>
       </Wall>	
	   <Wall>
           <Row>3</Row>
           <Column>14</Column>
       </Wall>	  
	   <Wall>
           <Row>3</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>4</Row>
           <Column>6</Column>
       </Wall>	 
	   <Wall>
           <Row>4</Row>
           <Column>15</Column>
       </Wall>	
	   <Wall>
           <Row>4</Row>
           <Column>16</Column>
       </Wall>	   
	   <Wall>
           <Row>5</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>4</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>6</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>8</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>9</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>10</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>11</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>12</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>6</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>6</Row>
           <Column>8</Column>
       </Wall>	 
	   <Wall>
           <Row>6</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>6</Row>
           <Column>14</Column>
       </Wall>	  
	   <Wall>
           <Row>6</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>7</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>7</Row>
           <Column>6</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>7</Row>
           <Column>8</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>11</Column>
       </Wall>	
	   <Wall>
           <Row>7</Row>
           <Column>13</Column>
       </Wall>	
	   <Wall>
           <Row>8</Row>
           <Column>3</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>8</Row>
           <Column>11</Column>
       </Wall>	  
	   <Wall>
           <Row>8</Row>
           <Column>13</Column>
       </Wall>	   
	   <Wall>
           <Row>8</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>16</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>3</Column>
       </Wall>	   
	   <Wall>
           <Row>9</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>9</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>9</Row>
           <Column>9</Column>
       </Wall>	  
	   <Wall>
           <Row>9</Row>
           <Column>11</Column>
       </Wall>	  
	   <Wall>
           <Row>9</Row>
           <Column>13</Column>
       </Wall>	
	   <Wall>
           <Row>10</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>9</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>11</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>13</Column>
       </Wall>	   
	   <Wall>
           <Row>10</Row>
           <Column>14</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>15</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>16</Column>
       </Wall>	   	   
	   <Wall>
           <Row>11</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>11</Row>
           <Column>7</Column>
       </Wall>	   
	   <Wall>
           <Row>11</Row>
           <Column>9</Column>
       </Wall>	  
	   <Wall>
           <Row>11</Row>
           <Column>11</Column>
       </Wall>
	   <Wall>
           <Row>11</Row>
           <Column>13</Column>
       </Wall>	   
	   <Wall>
           <Row>12</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>7</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>9</Column>
       </Wall>	
	   <Wall>
           <Row>12</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>13</Column>
       </Wall>	   
	   <Wall>
           <Row>13</Row>
           <Column>2</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>13</Row>
           <Column>4</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>13</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>13</Row>
           <Column>9</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>14</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>14</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>14</Row>
           <Column>9</Column>
       </Wall>	  
	   <Wall>
           <Row>14</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>4</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>6</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>15</Row>
           <Column>9</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>12</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>14</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>16</Column>
       </Wall>
	   <Wall>
           <Row>16</Row>
           <Column>9</Column>
       </Wall>
   </InsideItems>
</Maze>";
        private const string Level2Xml = @"<Maze>
   <Level>2</Level>
   <StartPoint>
       <Row>1</Row>
       <Column>9</Column>
   </StartPoint>
   <EscapePoint>
       <Row>17</Row>
       <Column>9</Column>
   </EscapePoint>
   <InsideItems>
       <Wall>
           <Row>2</Row>
           <Column>3</Column>
       </Wall>
	   <Wall>
           <Row>2</Row>
           <Column>12</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>3</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>5</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>6</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>7</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>8</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>9</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>10</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>12</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>14</Column>
       </Wall>	  
	   <Wall>
           <Row>3</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>4</Row>
           <Column>10</Column>
       </Wall>	 
	   <Wall>
           <Row>4</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>2</Column>
       </Wall>		   
	   <Wall>
           <Row>5</Row>
           <Column>3</Column>
       </Wall>	  	 
	   <Wall>
           <Row>5</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>6</Column>
       </Wall>	
	   <Wall>
           <Row>5</Row>
           <Column>7</Column>
       </Wall>		   
	   <Wall>
           <Row>5</Row>
           <Column>8</Column>
       </Wall>	    
	   <Wall>
           <Row>5</Row>
           <Column>10</Column>
       </Wall>	   
	   <Wall>
           <Row>5</Row>
           <Column>12</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>13</Column>
       </Wall>	 	   
	   <Wall>
           <Row>5</Row>
           <Column>15</Column>
       </Wall>
	   <Wall>
           <Row>6</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>6</Row>
           <Column>10</Column>
       </Wall>	 
	   <Wall>
           <Row>6</Row>
           <Column>13</Column>
       </Wall>	   
	   <Wall>
           <Row>6</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>2</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>7</Row>
           <Column>4</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>5</Column>
       </Wall>	  	 
	   <Wall>
           <Row>7</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>7</Row>
           <Column>8</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>9</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>10</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>11</Column>
       </Wall>		
	   <Wall>
           <Row>7</Row>
           <Column>12</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>13</Column>
       </Wall>	
	   <Wall>
           <Row>7</Row>
           <Column>15</Column>
       </Wall>	
	   <Wall>
           <Row>8</Row>
           <Column>7</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>15</Column>
       </Wall>	  	
	   <Wall>
           <Row>9</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>4</Column>
       </Wall>   
	   <Wall>
           <Row>9</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>6</Column>
       </Wall>  
	   <Wall>
           <Row>9</Row>
           <Column>7</Column>
       </Wall>	 	
	   <Wall>
           <Row>9</Row>
           <Column>9</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>10</Column>
       </Wall>  
	   <Wall>
           <Row>9</Row>
           <Column>11</Column>
       </Wall>	  
	   <Wall>
           <Row>9</Row>
           <Column>13</Column>
       </Wall>		
	   <Wall>
           <Row>9</Row>
           <Column>14</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>15</Column>
       </Wall>	
	   <Wall>
           <Row>10</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>13</Column>
       </Wall>	  
	   <Wall>
           <Row>11</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>11</Row>
           <Column>4</Column>
       </Wall>  
	   <Wall>
           <Row>11</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>11</Row>
           <Column>6</Column>
       </Wall>
	   <Wall>
           <Row>11</Row>
           <Column>7</Column>
       </Wall>		
	   <Trap>
           <Row>11</Row>
           <Column>8</Column>
       </Trap>   
	   <Wall>
           <Row>11</Row>
           <Column>9</Column>
       </Wall>		
	   <Wall>
           <Row>11</Row>
           <Column>10</Column>
       </Wall>  
	   <Wall>
           <Row>11</Row>
           <Column>11</Column>
       </Wall>	
	   <Wall>
           <Row>11</Row>
           <Column>12</Column>
       </Wall>
	   <Wall>
           <Row>11</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>11</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>11</Row>
           <Column>16</Column>
       </Wall>  
	   <Wall>
           <Row>12</Row>
           <Column>6</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>2</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>13</Row>
           <Column>4</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>6</Column>
       </Wall>	
	   <Wall>
           <Row>13</Row>
           <Column>8</Column>
       </Wall>	  
	   <Wall>
           <Row>13</Row>
           <Column>9</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>10</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>12</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>14</Column>
       </Wall>	 	
	   <Wall>
           <Row>13</Row>
           <Column>15</Column>
       </Wall>	
	   <Wall>
           <Row>14</Row>
           <Column>6</Column>
       </Wall>	  
	   <Wall>
           <Row>14</Row>
           <Column>10</Column>
       </Wall>	  
	   <Wall>
           <Row>14</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>4</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>6</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>15</Row>
           <Column>9</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>10</Column>
       </Wall>	   
	   <Wall>
           <Row>15</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>12</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>15</Column>
       </Wall>	 
	   <Trap>
           <Row>16</Row>
           <Column>13</Column>
       </Trap>
   </InsideItems>
</Maze>";
        private const string Level3Xml = @"<Maze>
   <Level>3</Level>
   <StartPoint>
       <Row>1</Row>
       <Column>9</Column>
   </StartPoint>
   <EscapePoint>
       <Row>17</Row>
       <Column>9</Column>
   </EscapePoint>
   <InsideItems>
       <Wall>
           <Row>2</Row>
           <Column>3</Column>
       </Wall>   
	   <Wall>
           <Row>3</Row>
           <Column>3</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>5</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>6</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>7</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>8</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>9</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>10</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>11</Column>
       </Wall>
	   <Wall>
           <Row>3</Row>
           <Column>12</Column>
       </Wall>	   
	   <Wall>
           <Row>3</Row>
           <Column>14</Column>
       </Wall>	  
	   <Wall>
           <Row>3</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>4</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>4</Row>
           <Column>12</Column>
       </Wall>		
	   <Wall>
           <Row>4</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>2</Column>
       </Wall>		   
	   <Wall>
           <Row>5</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>4</Column>
       </Wall>	  	 
	   <Wall>
           <Row>5</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>5</Row>
           <Column>7</Column>
       </Wall>	
	   <Wall>
           <Row>5</Row>
           <Column>9</Column>
       </Wall>		   
	   <Wall>
           <Row>5</Row>
           <Column>10</Column>
       </Wall>	    
	   <Wall>
           <Row>5</Row>
           <Column>11</Column>
       </Wall>	   
	   <Wall>
           <Row>5</Row>
           <Column>12</Column>
       </Wall>	  
	   <Wall>
           <Row>5</Row>
           <Column>13</Column>
       </Wall>	 	   
	   <Wall>
           <Row>5</Row>
           <Column>15</Column>
       </Wall>
	   <Wall>
           <Row>6</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>6</Row>
           <Column>7</Column>
       </Wall>	 
	   <Wall>
           <Row>6</Row>
           <Column>13</Column>
       </Wall>	   
	   <Wall>
           <Row>6</Row>
           <Column>15</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>3</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>7</Column>
       </Wall>	
	   <Wall>
           <Row>7</Row>
           <Column>8</Column>
       </Wall>
	   <Wall>
           <Row>7</Row>
           <Column>9</Column>
       </Wall>	  	 
	   <Wall>
           <Row>7</Row>
           <Column>10</Column>
       </Wall>	  
	   <Wall>
           <Row>7</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>7</Row>
           <Column>15</Column>
       </Wall>
	   <Wall>
           <Row>8</Row>
           <Column>5</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>7</Column>
       </Wall>	 
	   <Wall>
           <Row>8</Row>
           <Column>11</Column>
       </Wall>		
	   <Wall>
           <Row>8</Row>
           <Column>12</Column>
       </Wall>	  
	   <Wall>
           <Row>8</Row>
           <Column>13</Column>
       </Wall>	  
	   <Wall>
           <Row>8</Row>
           <Column>14</Column>
       </Wall>		
	   <Wall>
           <Row>8</Row>
           <Column>15</Column>
       </Wall>			
	   <Wall>
           <Row>9</Row>
           <Column>2</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>3</Column>
       </Wall>   
	   <Wall>
           <Row>9</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>7</Column>
       </Wall>  
	   <Wall>
           <Row>9</Row>
           <Column>8</Column>
       </Wall>	 	
	   <Wall>
           <Row>9</Row>
           <Column>9</Column>
       </Wall>	
	   <Wall>
           <Row>9</Row>
           <Column>11</Column>
       </Wall>
	   <Wall>
           <Row>10</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>9</Column>
       </Wall>	
	   <Wall>
           <Row>10</Row>
           <Column>11</Column>
       </Wall>		
	   <Wall>
           <Row>10</Row>
           <Column>13</Column>
       </Wall>	  
	   <Wall>
           <Row>10</Row>
           <Column>14</Column>
       </Wall>		
	   <Wall>
           <Row>10</Row>
           <Column>15</Column>
       </Wall>	
	   <Wall>
           <Row>11</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>11</Row>
           <Column>4</Column>
       </Wall>  
	   <Wall>
           <Row>11</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>11</Row>
           <Column>6</Column>
       </Wall>
	   <Wall>
           <Row>11</Row>
           <Column>7</Column>
       </Wall>		 
	   <Wall>
           <Row>11</Row>
           <Column>9</Column>
       </Wall>		
	   <Wall>
           <Row>11</Row>
           <Column>13</Column>
       </Wall>
	   <Wall>
           <Row>12</Row>
           <Column>7</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>9</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>10</Column>
       </Wall>	  
	   <Wall>
           <Row>12</Row>
           <Column>11</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>12</Column>
       </Wall>	
	   <Wall>
           <Row>12</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>14</Column>
       </Wall>	 
	   <Wall>
           <Row>12</Row>
           <Column>15</Column>
       </Wall>	
	   <Wall>
           <Row>12</Row>
           <Column>16</Column>
       </Wall>
	   <Wall>
           <Row>13</Row>
           <Column>2</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>3</Column>
       </Wall>	  
	   <Wall>
           <Row>13</Row>
           <Column>4</Column>
       </Wall>	 
	   <Wall>
           <Row>13</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>13</Row>
           <Column>7</Column>
       </Wall>	  	 
	   <Trap>
           <Row>13</Row>
           <Column>14</Column>
       </Trap>	 
	   <Wall>
           <Row>14</Row>
           <Column>5</Column>
       </Wall>	  
	   <Wall>
           <Row>14</Row>
           <Column>7</Column>
       </Wall>	  
	   <Wall>
           <Row>14</Row>
           <Column>8</Column>
       </Wall>		
	   <Wall>
           <Row>14</Row>
           <Column>9</Column>
       </Wall> 	 
	   <Wall>
           <Row>14</Row>
           <Column>10</Column>
       </Wall>	 
	   <Wall>
           <Row>14</Row>
           <Column>11</Column>
       </Wall>	
	   <Wall>
           <Row>14</Row>
           <Column>12</Column>
       </Wall>	 
	   <Wall>
           <Row>14</Row>
           <Column>13</Column>
       </Wall>	 
	   <Wall>
           <Row>14</Row>
           <Column>14</Column>
       </Wall>	
	   <Wall>
           <Row>14</Row>
           <Column>15</Column>
       </Wall>
	   <Wall>
           <Row>15</Row>
           <Column>3</Column>
       </Wall>	 
	   <Wall>
           <Row>15</Row>
           <Column>5</Column>
       </Wall>	
	   <Wall>
           <Row>15</Row>
           <Column>8</Column>
       </Wall>	 
	   <Wall>
           <Row>16</Row>
           <Column>3</Column>
       </Wall>	
	   <Wall>
           <Row>16</Row>
           <Column>8</Column>
       </Wall>	 
	   <Wall>
           <Row>16</Row>
           <Column>11</Column>
       </Wall>
   </InsideItems>
</Maze>";

        private string Level1Result = @"<Actions>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>1</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>3</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>3</Direction>
    		<CellNumber>6</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>3</CellNumber>
    	</Step>
    	<Step>
    		<Direction>3</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>7</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>1</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>1</CellNumber>
    	</Step>
    </Actions>
".Replace(" ", string.Empty);
        private string Level2Result = @"<Actions>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>1</CellNumber>
    	</Step>
    	<Step>
    		<Direction>1</Direction>
    		<CellNumber>5</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>5</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>1</Direction>
    		<CellNumber>3</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>1</Direction>
    		<CellNumber>4</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>4</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>3</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>1</Direction>
    		<CellNumber>3</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>2</CellNumber>
    	</Step>
    	<Step>
    		<Direction>2</Direction>
    		<CellNumber>7</CellNumber>
    	</Step>
    	<Step>
    		<Direction>4</Direction>
    		<CellNumber>1</CellNumber>
    	</Step>
    </Actions>
".Replace(" ", string.Empty);
        private string Level3Result = @"".Replace(" ", string.Empty);
        #endregion

        [TestMethod]
        public void TestLevel1()
        {
            Maze maze = new Maze(Level1Xml);
            Agency agency = new Agency(maze);
            Agent best = agency.Solve();
            Assert.AreEqual(Level1Result, best.Result().Replace(" ", string.Empty));
        }

        [TestMethod]
        public void TestLevel2()
        {
            Maze maze = new Maze(Level2Xml);
            Agency agency = new Agency(maze);
            Agent best = agency.Solve();
            Assert.AreEqual(Level2Result, best.Result().Replace(" ", string.Empty));
            
        }

        [TestMethod]
        public void TestLevel3()
        {
            Task<string> solver = new Task<string>(() =>
            {
                Maze maze = new Maze(Level3Xml);
                Agency agency = new Agency(maze);
                Agent best = agency.Solve();
                return best.Result();
            });

            Task timeout = Task.Delay(60 * 1000);

            Task.WaitAny(solver, timeout);

            try
            {
                Assert.IsFalse(solver.IsFaulted);
                Assert.IsTrue(solver.IsCompleted);
            }
            catch
            {
                throw;
            }

            Logger.LogMessage(solver.Result);
        }
    }
}